###
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "email": "felt@outlook.ggg",
    "password": "admin2s",
}

###
GET http://localhost:5000/api/users

###
GET http://localhost:5000/api/users/1